name: Node.js CD

on:
  push:
    branches:
      - main

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: 🚀 Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_KEYS }}
          port: 22
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh 
            cd /var/www/iot-api
            git pull
            npm install
            pm2 restart iot-server
